import type { CommunityPost } from "@/types";

const now = Date.now();
const minutesAgo = (m: number) => new Date(now - m * 60_000).toISOString();
const hoursAgo = (h: number) => new Date(now - h * 3_600_000).toISOString();

export const MOCK_POPULAR: CommunityPost[] = [
  {
    id: "p1",
    title: "75만원으로 시작한거",
    body: "",
    preview: "처음 코인 시장에 들어왔을 때 75만원으로 시작했던 이야기를 풀어봅니다.",
    author: "초심자K",
    avatar: "🐤",
    category: "Lounge",
    publishedAt: hoursAgo(16),
    likes: 412,
    commentsCount: 87,
    views: 12400,
    tags: ["회고"],
    postKind: "free",
  },
  {
    id: "p2",
    title: "XRP",
    body: "",
    preview: "최근 흐름 정리 — 추세선이 다시 살아나는 구간으로 보입니다.",
    author: "체인리더",
    avatar: "🐉",
    category: "Chart Analysis",
    publishedAt: hoursAgo(18),
    likes: 188,
    commentsCount: 34,
    views: 5400,
    tags: ["XRP"],
    postKind: "analysis",
  },
  {
    id: "p3",
    title: "Clarity Act 상원 통과 일정",
    body: "",
    preview: "이번 주 상원에서 클래리티 액트 표결 일정이 잡혔습니다. 시장 영향 정리.",
    author: "Macro Desk",
    avatar: "📡",
    category: "News Reactions",
    publishedAt: hoursAgo(18),
    likes: 222,
    commentsCount: 41,
    views: 7800,
    tags: ["규제", "미국"],
    postKind: "news",
  },
];

export const MOCK_FEED: CommunityPost[] = [
  {
    id: "f1",
    title: "9시 초기화 전 출석 회고",
    body: "",
    preview: "토요일 출석 깜빡하지 마세요~ 이번 주 이벤트 마감 전 정리합니다.",
    author: "요우무",
    avatar: "🐼",
    category: "Lounge",
    publishedAt: minutesAgo(2),
    likes: 3,
    commentsCount: 1,
    views: 28,
    tags: [],
    postKind: "free",
  },
  {
    id: "f2",
    title: "오늘 BTC 단기 흐름 어떻게 보세요?",
    body: "",
    preview: "78k 지지 한 번 더 확인하면 반등 시도 가능해 보이는데, 다들 어떻게 보시나요?",
    author: "체인리더",
    avatar: "🐉",
    category: "BTC Market Thoughts",
    publishedAt: minutesAgo(14),
    likes: 28,
    commentsCount: 12,
    views: 410,
    tags: ["BTC"],
    stance: "Neutral",
    postKind: "analysis",
  },
  {
    id: "f3",
    title: "에어드롭 미션 끝나기 전에 마지막 체크",
    body: "",
    preview: "오늘 자정 마감입니다. 미션 페이지에서 보상 받는 거 잊지 마세요.",
    author: "AirdropBot",
    avatar: "🎁",
    category: "Event",
    publishedAt: minutesAgo(38),
    likes: 91,
    commentsCount: 6,
    views: 1200,
    tags: ["에어드롭"],
    postKind: "event",
  },
  {
    id: "f4",
    title: "ETH 2,180 라인이 핵심",
    body: "",
    preview: "이 라인 깨지면 단기 약세 연장 가능. 깨지지 않으면 다시 2.25k 시도.",
    author: "Macro Desk",
    avatar: "📡",
    category: "Chart Analysis",
    publishedAt: hoursAgo(1),
    likes: 64,
    commentsCount: 22,
    views: 980,
    tags: ["ETH"],
    stance: "Bearish",
    postKind: "analysis",
  },
  {
    id: "f5",
    title: "Clarity Act, 통과되면 알트 영향은?",
    body: "",
    preview: "법안 핵심 요약과 알트코인 분류 기준에 미치는 영향 정리해봤습니다.",
    author: "RegWatch",
    avatar: "🦉",
    category: "News Reactions",
    publishedAt: hoursAgo(3),
    likes: 154,
    commentsCount: 47,
    views: 3400,
    tags: ["규제"],
    postKind: "news",
  },
];

export async function fetchCommunityPosts(): Promise<{
  popular: CommunityPost[];
  feed: CommunityPost[];
}> {
  return { popular: MOCK_POPULAR, feed: MOCK_FEED };
}
