export type Article = {
  id: string;
  title: string;
  slug: string;
  sourceId: string;
  sourceName: string;
  originalUrl: string;
  publishedAt: string;
  excerpt: string;
  category: string;
  tags: string[];
  readingTime: string;
  briefSummary: string;
  rawContentSnippet: string;
  feedCategory?: string;
  customCategory?: string;
  marketType?: string;
  region?: string;
  tickerSymbol?: string;
};
